SUM/AVG aggregation throws IllegalStateException on VARIANT typed inputs instead of lowering (#1889)
## Relevant Issues
`SELECT SUM(t.v) FROM << {'v': `1`}, {'v': `2`}, {'v': `3`} >> AS t;`
Expected:
```
<< { '_1': 6 } >>
```

Actual:
```
java.lang.IllegalStateException: Unexpected type: VARIANT at org.partiql.spi.function.builtins.internal.AccumulatorSumDynamic.nextValue(AccumulatorSum.kt:95)
```
## Description
- Apply Datum.lower when using AVG and SUM

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**: <Explain if NO>
- Any backward-incompatible changes? **[YES/NO]**: <Explain if YES>
- Any new external dependencies? **[YES/NO]**: <Explain if YES>
- Do your changes comply with the [contributing][cg] and [code
style][csg] guidelines? **[YES/NO]**

## License Information

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

<!-- DO NOT DELETE BELOW -->

[cg]:
https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md
[csg]:
https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md