Revert "Redefine non-standard DATE_ADD to interval arithmetic #1690" (#1896)
This reverts commit e433e194afebe7554e11c318d7125234bd99cc16.

## Description
```
partiql ▶ date_add(year, 1, `2017T`);

=== RESULT ===
TIMESTAMP '2018-01-01T00:00'

OK!

partiql ▶ DATE_ADD(day, - (4 * 365 + 30), UTCNOW());
e: [semantic] Unexpected failure encountered. Caused by: java.lang.ClassCastException: class org.partiql.planner.internal.ir.Rex$Op$Call$Unresolved cannot be cast to class org.partiql.planner.internal.ir.Rex$Op$Lit (org.partiql.planner.internal.ir.Rex$Op$Call$Unresolved and org.partiql.planner.internal.ir.Rex$Op$Lit are in unnamed module of loader 'app').
java.lang.ClassCastException: class org.partiql.planner.internal.ir.Rex$Op$Call$Unresolved cannot be cast to class org.partiql.planner.internal.ir.Rex$Op$Lit (org.partiql.planner.internal.ir.Rex$Op$Call$Unresolved and org.partiql.planner.internal.ir.Rex$Op$Lit are in unnamed module of loader 'app')
	at org.partiql.planner.internal.transforms.RexConverter$ToRex.visitExprCallDateAddFunction(RexConverter.kt:742)
	at org.partiql.planner.internal.transforms.RexConverter$ToRex.visitExprCall(RexConverter.kt:647)
	at org.partiql.planner.internal.transforms.RexConverter$ToRex.visitExprCall(RexConverter.kt:140)
	at org.partiql.ast.expr.ExprCall.accept(ExprCall.java:47)
	at org.partiql.planner.internal.transforms.RexConverter$ToRex.visitExprCoerce(RexConverter.kt:285)
	at org.partiql.planner.internal.transforms.RexConverter$ToRex.visitExprCoerce$default(RexConverter.kt:280)
	at org.partiql.planner.internal.transforms.RexConverter.apply$partiql_planner(RexConverter.kt:136)
	at org.partiql.planner.internal.transforms.AstToPlan$ToPlanStatement.visitQuery(AstToPlan.kt:46)
	at org.partiql.planner.internal.transforms.AstToPlan$ToPlanStatement.visitQuery(AstToPlan.kt:39)
	at org.partiql.ast.Query.accept(Query.java:34)
	at org.partiql.planner.internal.transforms.AstToPlan.apply(AstToPlan.kt:37)
	at org.partiql.planner.internal.SqlPlanner.plan(SqlPlanner.kt:44)
	at org.partiql.cli.pipeline.Pipeline$plan$result$1.invoke(Pipeline.kt:50)
	at org.partiql.cli.pipeline.Pipeline$plan$result$1.invoke(Pipeline.kt:49)
	at org.partiql.cli.pipeline.Pipeline.listen(Pipeline.kt:67)
	at org.partiql.cli.pipeline.Pipeline.plan(Pipeline.kt:49)
	at org.partiql.cli.pipeline.Pipeline.execute(Pipeline.kt:34)
	at org.partiql.cli.shell.Shell.run(Shell.kt:267)
	at org.partiql.cli.shell.Shell.start(Shell.kt:149)
	at org.partiql.cli.MainCommand.shell(Main.kt:193)
	at org.partiql.cli.MainCommand.run(Main.kt:171)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.partiql.cli.Main.main(Main.kt:46)

Failed with given input. Please see the above errors.

```

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**: <Explain if NO>
- Any backward-incompatible changes? **[YES/NO]**: <Explain if YES>
- Any new external dependencies? **[YES/NO]**: <Explain if YES>
- Do your changes comply with the [contributing][cg] and [code
style][csg] guidelines? **[YES/NO]**

## License Information

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

<!-- DO NOT DELETE BELOW -->

[cg]:
https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md
[csg]:
https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md